### PR TITLE
Feature/configure auto index v1

### PR DESCRIPTION
**Pull request by meshuga**

### CODE REVIEW

**Comment by alexcojocaru** [comment]
Thank you. I will start the release process right away, it will take a couple of hours before the artifact will show up in the maven central repo.

**Comment by alexcojocaru** [comment]
Correction: I will start the release process later today.

**Comment by meshuga** [comment]
Thanks!

**Comment by alexcojocaru** [comment]
I have just released v1.13 of the plugin. Here's the direct link to it:
https://search.maven.org/#artifactdetails|com.github.alexcojocaru|elasticsearch-maven-plugin|1.13|maven-plugin
The search index on the maven central repo will take a few hours to refresh.

**Pull request merged**
