### PR TITLE
Version 5.0 with support for ES 5

### PR DESCRIPTION
**Pull request by yrodiere**
With the recent release of ES 5.0, an upgrade might be a good idea :)

Here is a first attempt. It's not really polished, but I think it's a good start: it launches the instance and passes the tests.

What's missing (I didn't really look into it):
- A log4j2 example configuration
- A way for users to manage the netty4 plugin version (or we can let them override the dependency, but this should be documented)
- Multicast support? (it's been removed from ES)
- Updating the documentation?

Any chance this can get merged and released? Do you need me to do something else before?

Thanks.

### CODE REVIEW

**Comment by yrodiere** [comment]
I made some research, and it seems embedded mode is not supported in Elasticsearch:

 * They don't publish modules/plugins JARs anymore: https://github.com/elastic/elasticsearch/issues/18131#issuecomment-222105133
 * They explicitly state they won't support it on their website: https://www.elastic.co/blog/elasticsearch-the-server#_embedded_elasticsearch_not_supported

I guess it's really bad news for elasticsearch-maven-plugin.

On a side-note, the Elasticsearch team seems to recommend using the following solution to run integration tests on an Elasticsearch instance: http://david.pilato.fr/blog/2016/10/18/elasticsearch-real-integration-tests-updated-for-ga/

**Comment by dadoonet** [comment]
@yrodiere Indeed that is becoming harder. On the other hand, have a look at https://github.com/elastic/elasticsearch/issues/21119.
I'm sure we would welcome a way to make that happen. cc @nik9000 

May be a way for the maven plugin to actually do all the stuff I wrote as an ANT script would be a good idea? So you don't really start embedded nodes but you do start elasticsearch nodes which can be accessible from the outside?

**Comment by nik9000** [comment]
> I'm sure we would welcome a way to make that happen. cc @nik9000

Yeah, I'd be happy to help here or elsewhere. I'm over committed but, I still think this is important.

And yeah, running embedded rather than forking the startup script is probably going to be a maintenance nightmare. You could start Elasticsearch and maven suddenly finds itself running with java security on and seccomp preventing it from forking.

**Comment by alexcojocaru** [comment]
@yrodiere Does this recent change to ES (in regard to the embedded version not being supported any longer) mean this merge request of yours to add ES 5 support is a no go?

@nik9000 I agree that continuing to use the embedded ES in the plugin could turn into a nightmare. There were some issues (eg. logging) which I had to deal with in previous versions, and that was not fun.

At this point, I am considering a rewrite of the ES maven plugin, to provide support for dealing with a self-contained ES package instead of relying on the embedded server. The plugin would download ES, update the config files as requested by the plugin config, and start the server. This is a very simplistic description, but that's how I would start.
It would be possible to reuse some of the existing code (mainly the code around running a script against the server).
@dadoonet Do you have any thoughts or suggestions on the above?

**Comment by yrodiere** [comment]
@alexcojocaru Yes, this PR is a no-go for two reasons:

 1. The embedded mode is not supported (which I didn't know when I submitted my PR)
 2. The ES team doesn't publish some essential modules on maven anymore, such as lang-groovy or lang-painless.

So the PR works, but without code modules it's not very useful, and maintenance work will probably be a nightmare.

If you're considering a full rewrite that will download an ES package, do you think you could use Maven-published distributions such as [this one](http://search.maven.org/#artifactdetails%7Corg.elasticsearch.distribution.zip%7Celasticsearch%7C5.0.0%7Cpom)?

Don't hesitate to ask if you need help for the rewrite. We (the Hibernate Search team) are considering support for Elasticsearch 5.0, and the sooner elasticsearch-maven-plugin is updated, the better :)

**Comment by alexcojocaru** [comment]
Just a quick update on my progress: the code is in the `es5` branch and is 90% complete. I am not planning any major refactoring from now on.

The code coverage through unit testing is very low; the integration testing is much much better.
Once I add a few more integration tests, I am considering releasing the new plugin (v5.0) in a few days from now.

Compared to the existing code base (master branch), the new plugin doesn't support custom data and/or logs directories, and also doesn't support keeping the existing data (this behavior would work hand in hand with custom data and/or logs directories though).

If any one of you needs support for custom data/log directories and is willing to help, let me know.

**Pull request closed without merging**
